### ISSUE TITLE
Winding the clock back? authoritarianism?

### ISSUE THREAD

**Issue by broukema** [apontzen/london_cc#7]
The aim of this issue is to allow people to respond, provide arguments for/against, if they disagree with the concern that many versions of the London Code of Conduct, including commit 85a18a6, appear to wind back the clock to authoritarian traditions, defeating the point of trying to conduct science workshops/conferences in a way that is fair to all participants. The [Inhomogeneous Cosmologies Toruń](https://cosmo.torun.pl/cosmotorun17_coc.html) was the result of much internal discussion in the organising committee; one element was replacing the authoritarian aspects of the London Code of Conduct by non-authoritarian procedures (the right of organisers to discuss an incident either publicly or privately, as appropriate). 

The argument presented in this *issue* is that the expressions **"comply immediately"**, **"violating these rules"**, **"leave the event at the sole discretion of the organizers without a refund of any charge"** give the impression of being authoritarian procedures:
   * the spirit of [habeas corpus](https://en.wikipedia.org/wiki/Habeas_corpus) appears to be violated - absolute authority is given to the "organizers" to evict (not imprison!) a participant without any chance of appeal
   * there is no reference to the informal equivalent of the [right to a fair trial](https://en.wikipedia.org/wiki/Right_to_a_fair_trial) - "organizers" make a decision at their "sole discretion"
   * there is no reference to the [presumption of innocence](https://en.wikipedia.org/wiki/Presumption_of_innocence)
 
_(Other issues debated in the committee included how prominent the code of conduct text should be on the meeting website, and whether or not to have a code of conduct at all. Empirical evidence in favour of having a code of conduct in the astronomy context included [Brough et al 2011 ArXiv:1106.6094](https://arxiv.org/abs/1106.6094); [Matteucci & Gratton 2014 ArXiv:1402.1952](https://arxiv.org/abs/1402.1952); [Schmidt et al 2017 ArXiv:1704.05260](https://arxiv.org/abs/1704.05260). This is not raised as a separate issue here, because within the committee, as far as I remember, there were no counterarguments raised against this evidence.)_

**Comment by apontzen** [comment]
I merged your PR so organizing committees can see the alternative version and make up their own mind where they want to branch from. I don’t think discussing further on a github issue will be productive.

**Comment by broukema** [comment]
I guess we have to agree to disagree about where the appropriate forum for discussion is. I don't really see the point of posting a text on a public git repository if discussion about the text is not directly associated with it. Especially since there's no obvious link to an appropriate online forum for discussing whether to/how to modify the text and why/why not. The geek feminism wiki goes beyond the astronomy community and I didn't see anything obvious there.

In any case, I've put a copy of the issue as [broukema/london_cc issue 1](https://github.com/broukema/london_cc/issues/1) so that people can discuss the 85a18a6 version over there if they wish.

Thanks for the merge. :)
